# IMPORTANT
# C:/Program Files/EasyPHP-WebServer-dev-14.1 is used to specify EasyPHP installation path
#
# This is for a system with little memory (32M - 64M) where MySQL plays
# an important part, or systems up to 128M where MySQL is used together with
# other programs (such as a web server)
#
# MySQL programs look for option files in a set of
# locations which depend on the deployment platform.
# You can copy this option file to one of those
# locations. For information about these locations, see:
# http://dev.mysql.com/doc/mysql/en/option-files.html
#
# In this file, you can use all long options that a program supports.
# If you want to know which options a program supports, run the program
# with the "--help" option.


# The following options will be passed to all MySQL clients
[client]
port = 3388

# EWS
pipe
socket="D:/gitlab/SiteWeb-Coussa/EasyPHP-Webserver-14.1b2/binaries/dbserver/data/mysql.sock"

# The MySQL server
[mysqld]
# The TCP/IP Port the MySQL Server will listen on
port = 3388

# Path to installation directory. All paths are usually resolved relative to this.
basedir = "D:/gitlab/SiteWeb-Coussa/EasyPHP-Webserver-14.1b2/binaries/dbserver/"

# Path to the database root
datadir = "D:/gitlab/SiteWeb-Coussa/EasyPHP-Webserver-14.1b2/binaries/dbserver/data/"

# The default storage engine that will be used when create new tables
default-storage-engine = MYISAM

log_error = "D:/gitlab/SiteWeb-Coussa/EasyPHP-Webserver-14.1b2/binaries/dbserver/data/mysql_error.log"
skip-external-locking
key_buffer_size = 32M
max_allowed_packet = 1M
table_open_cache = 64
sort_buffer_size = 512K
net_buffer_length = 8K
read_buffer_size = 256K
read_rnd_buffer_size = 512K
myisam_sort_buffer_size = 8M

# Don't listen on a TCP/IP port at all. This can be a security enhancement,
# if all processes that need to connect to mysqld run on the same host.
# All interaction with mysqld must be made via Unix sockets or named pipes.
# Note that using this option without enabling named pipes on Windows
# (via the "enable-named-pipe" option) will render mysqld useless!
#
#skip-networking
#enable-named-pipe

# EWS
socket="C:/Program Files/EasyPHP-Webserver-14.1b1/binaries/dbserver/data/mysql.sock"
bind-address=127.0.0.1
skip-show-database
skip-name-resolve
skip-host-cache

[mysqldump]
quick
max_allowed_packet = 16M

[mysql]
no-auto-rehash
# Remove the next comment character if you are not familiar with SQL
#safe-updates

[isamchk]
key_buffer = 20M
sort_buffer_size = 20M
read_buffer = 2M
write_buffer = 2M

[myisamchk]
key_buffer_size = 20M
sort_buffer_size = 20M
read_buffer = 2M
write_buffer = 2M

[mysqlhotcopy]
interactive-timeout
