<?php
/**
 * EasyPHP: a complete and ready-to-use WAMP environment for
 * PHP development (Devserver) and self hosting (Webserver)
 * build with PHP, Apache, MySQL, PhpMyAdmin, Xdebug and more.
 *
 * EASYPHP WEBSERVER MODULE
 * @author   Laurent Abbal <laurent@abbal.com>
 * @link     http://www.easyphp.org
 */
 ?>

<div class="container">

	<div class='row'>
		<div class="col-sm-2">
			<div class="list-group">
				<a href="index.php" class="list-group-item disabled"><small class="glyphicon glyphicon-chevron-left"></small> <strong>Dashboard</strong></a>
				<a href="index.php?zone=settings" class="list-group-item">System</a>
				<a href="index.php?zone=settings&page=php" class="list-group-item">PHP</a>

				<?php
				$binaries = @opendir('../binaries');

				while ($binaries_dir = @readdir($binaries)){
					if (@file_exists('../binaries/'.$binaries_dir.'/ews_app.php')){
						include('../binaries/'.$binaries_dir.'/ews_app.php');
						echo '<a href="index.php?zone=settings&page=' . $server['app_folder'] . '" class="list-group-item">' . strtoupper($server['app_type_name']) . '</a>';
					}
				}
				@closedir($binaries);
				?>

			</div>
		</div>
		
		<div class="col-sm-10">
			<?php
			if ($_GET['page'] == "") {
			?>
			
				<div class="row">
					<div class="col-sm-1">
						<img src="images/ews_icon_webserver.png" border="0" />
					</div>
					<div class="col-sm-11">
						<h1>SYSTEM</h1>
						<p>
							<small><em>application : </em>EasyPHP Webserver</small></br>
							<small><em>version : 14.1</em></small></br>
							<small><em>website : </em><a href='http://www.easyphp.org' target="_blank">www.easyphp.org</a></small>
						</p>
					</div>
				</div>
				<br />
				
				<?php
				exec("service-info.exe query ews-dashboard",$service_status);
				$ews_service_install = "service-install install ews-dashboard";

				if (count($service_status) == 1)
				{
					// service not installed -> install service
					$control = '<form method="post" action="http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'] . '" class="form-inline" role="form">';
					$control .= '<input type="hidden" name="app_service_control" value="' . $ews_service_install . '" />';
					$control .= '<button type="submit" class="btn btn-primary btn-sm" onclick="delay()"><strong>install service</strong></button>';
					$control .= '</form>';
				} else {
					// service installed
					$control = '<div class="alert alert-warning" role="alert" style="margin-right:20px;border-color: #fcf8e3;"><strong>How to stop or remove the service ?</strong><br />';
					$control .= 'You cannot stop or remove the service from this page as the content of this page is generated by the service itself.<br />';
					$control .= 'To stop or remove the service you have to use an external tool : "Service Manager" ( <samp>' . dirname(getcwd()) . '\tools\ServiceManager.exe</samp> )<br /><br />';
					$control .= '<ul>';
					$control .= '<li>If you stopped the service and want to open this page again you need to use the launcher (<samp>' . getcwd() . '\ews-launcher.exe</samp> or its shorcut in the Start Menu or Start Screen) or to restart the service with ServiceManager.exe</li>';
					$control .= '<li>If you removed the service and want to open this page again you need to use the launcher.</li>';
					$control .= '</ul>';
					$control .= '</div>';
				}
				?>
				<div class="table-responsive">
					<table class="table">
						<tbody>
							<tr>
								<td><strong>Service</strong></td>
								<td>
									A Windows service is a computer program that operates in the background.
									The service is configured to start when the operating system starts, and run in the background as long as Windows is running. If Windows restarts, the service restarts automatically.
									If you want to have the dashboard and "settings" accessible all the time, you can install EasyPHP Webserver as a service (you will not need the launcher anymore).
									<br /><br />
									<?php echo $control; ?>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			<?php
			} elseif($_GET['page'] == "php") {
				?>
				<div class="row">
					<div class="col-sm-1">
						<img src="images/ews_icon_php.png" border="0" />
					</div>
					<div class="col-sm-11">
						<h1>PHP</h1>
						<p>
							<small><em>version : </em>5.4.30</small></br>
							<small><em>website : </em><a href='http://php.net/' target="_blank">php.net</a></small>
						</p>
					</div>
				</div>
				<br />
				<p>
					<strong>Files & parameters :</strong>
					<a href="index.php?zone=settings&page=php&display=phpconffile"><button type="button" class="btn btn-info btn-xs">Configuration File</button></a>
				</p>

				<?php
				if ($_GET['display'] == 'phpconffile') {
					?>
					<a href="index.php?zone=settings&page=php"><button type="button" class="close"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button></a>
					<h2>PHP Configuration</h2>	
					<pre><?php echo htmlspecialchars(file_get_contents('../binaries/httpserver/conf/httpd.conf', FILE_USE_INCLUDE_PATH)); ?></pre>
					<?php
				}

			} else {
				include('../binaries/' . $_GET['page'] . '/ews_app.php');
				?>
				<div class="row">
					<div class="col-sm-1">
						<?php
						echo '<img src="images/' . $server['app_icon'] . '" border="0" />';
						?>
					</div>
					<div class="col-sm-11">
						<h1><?php echo strtoupper($server['app_type_name']) ?></h1>
						<p>
							<small><em>application : </em><?php echo $server['app_name'] ?></small></br>
							<small><em>version : </em><?php echo $server['app_version'] ?></small></br>
							<small><em>website : </em><a href='<?php echo $server['app_website_url'] ?>' target="_blank"><?php echo $server['app_website'] ?></a></small>
						</p>
					</div>
				</div>
				<br />
				<?php
				include('../binaries/' . $_GET['page'] . '/ews_app_settings.php');
			}
			?>
		</div>
	</div>
</div> <!-- /container -->